### PR TITLE
Add config option to power off into art mode

### PR DESCRIPTION
**Pull request by idoaflalo**
Some TV models like "The Frame TV", when you power them off the TV stays on with the art mode (in order to be a frame picture).
This pull request adds an option to the configuration of the device to make change the behavior of the power off functionality in order to function like the power off button on the remote control.

### CODE REVIEW

**Comment by ollo69** [comment]
Already exist a dedicated service to control this, that can be simply associated to a dedicated button in UI. This integration already have tons of options, I prefer avoid to add a new one,

**Comment by idoaflalo** [comment]
> Already exist a dedicated service to control this, that can be simply associated to a dedicated button in UI. This integration already have tons of options, I prefer avoid to add a new one,

Yes, but if I want to turn off the TV(media player) from Google assistant, I cant do that because "The Frame TV" does not support this function.
This feature is actually necessary for some Samsung models in order to control the power state properly.
Moreover, when you add the entity to lovelace, you want the power control to function properly without the need to add a spacial button only for powering off the TV...
Again this feature is necessary in order to support those TV models.
Hope you understand.

**Comment by supercoolrepo** [comment]
> Some TV models like "The Frame TV", when you power them off the TV stays on with the art mode (in order to be a frame picture). This pull request adds an option to the configuration of the device to make change the behavior of the power off functionality in order to function like the power off button on the remote control.

I need this feature too. Currently, can't turn off my frame TV properly.

**Comment by 44ofir** [comment]
I’ve been waiting for this feature for so long time! Have this kind of TV, and it is so annoying I cannot turn the art mode on remotely. Thank you! It will be very helpful feature…

**Comment by ollo69** [comment]
My concern is that this PR is going the break the real power off. I understand that you want to use the power button to set the TV in art mode, but how you will power off the TV at all? Changing the behavior of the `async_turn_off` will also change the behavior of related serivice `media_player.turn_off` the use this method. It is very simply use a custom control as [mini media player](https://github.com/kalkih/mini-media-player) to add a button associated to the service `set_art mode`.

**Comment by idoaflalo** [comment]
> My concern is that this PR is going the break the real power off. I understand that you want to use the power button to set the TV in art mode, but how you will power off the TV at all? Changing the behavior of the `async_turn_off` will also change the behavior of related serivice `media_player.turn_off` the use this method. It is very simply use a custom control as [mini media player](https://github.com/kalkih/mini-media-player) to add a button associated to the service `set_art mode`.

In "The frame TV" series, the TV doesn't have the ability to turn off completely (only to go into art mode).
That means when I "power off" the TV using the original remote control, it doesn't turn it off but rather goes into art mode.
That's the goal of this pull request.
If the user wants the default behavior, he shouldn't check this option in the settings

**Comment by ollo69** [comment]
> In "The frame TV" series, the TV doesn't have the ability to turn off completely (only to go into art mode).
> That means when I "power off" the TV using the original remote control, it doesn't turn it off but rather goes into art mode.

This is valid for all "The Frame TV"? I just take a look to manuals from some models some times ago, and I also have some discussion in other threads where people said to me that exist 3 states: On -> Art Mode -> Off, and state change pushing more times the remote power button. If this is a feature for your specific model, should be interesting try to determinate this at run-time instead adding a new option. What information you receive when you open in a browser the page `http://{tv host}:8001/api/v2/`?

**Comment by ollo69** [comment]
But there are no way for you to fully turn-off your TV (excluding unplugging the power of course, I mean go yo stand-by and not art mode)? I suppose that art-mode still consume power, and probably is not so good have a device on when, for instance, you are not at home.

**Comment by idoaflalo** [comment]
> But there are no way for you to fully turn-off your TV (excluding unplugging the power of course, I mean go yo stand-by and not art mode)? I suppose that art-mode still consume power, and probably is not so good have a device on when, for instance, you are not at home.

The point of "The frame TV" is to be a picture when you are not using it. At night there is a sensor in the TV which recognizes whether there is no one around and then turns the display off. When someone is detected with the sensor the display gets on again.
This night mode has to be enabled in the settings of the TV (default is always on).

**Comment by idoaflalo** [comment]
https://www.samsung.com/uk/lifestyle-tvs/the-frame/highlights/

**Comment by ollo69** [comment]
Anyway looking at the manual turn off the TV is possible keeping the art mode button on remote pressed. Just to understand, if you now press the power button on HA when TV is on, what happen? 
I think that this option should:
- first check if TV support art mode to show the options in the configuration menu only when requested (we can determinate this from TV info)
- Use the method `toggle` (currently not implemented) to behave different only for TV with art mode and with the option enabled.

**Comment by ripburger** [comment]
When I call the service media_player.turn_off, my 2021 Samsung The Frame turns off completely (energy consumption meter shows 0). Calling the service samsungtv_smart.set_art_mode sets it to Art Mode. Or am I missing the point here?

**Comment by idoaflalo** [comment]
> Anyway looking at the manual turn off the TV is possible keeping the art mode button on remote pressed. Just to understand, if you now press the power button on HA when TV is on, what happen? I think that this option should:
> 
> * first check if TV support art mode to show the options in the configuration menu only when requested (we can determinate this from TV info)
> * Use the method `toggle` (currently not implemented) to behave different only for TV with art mode and with the option enabled.

That could be a possible solution.

**Comment by idoaflalo** [comment]
> When I call the service media_player.turn_off, my 2021 Samsung The Frame turns off completely (energy consumption meter shows 0). Calling the service samsungtv_smart.set_art_mode sets it to Art Mode. Or am I missing the point here?

Yes it does but it shouldn't (otherwise why did you buy this TV). When you press the power button on your remote control multiple times, what states the TV goes into?

**Comment by ollo69** [comment]
I just released a new version (beta release) to implement this change. The option is available as advanced option. Please test it and let me know if it work properly with your TV.

**Comment by idoaflalo** [comment]
> I just released a new version (beta release) to implement this change. The option is available as advanced option. Please test it and let me know if it work properly with your TV.

Sometimes it works and sometimes not (mostly goes into black screen - off state).

**Comment by ollo69** [comment]
Please try to be a little bit more detailed. What are the condition that send the TV in off state? Is related to timing (remember that refresh polling is 15 seconds).

**Comment by idoaflalo** [comment]
> Please try to be a little bit more detailed. What are the condition that send the TV in off state? Is related to timing (remember that refresh polling is 15 seconds).

When I toggle the power button few times, the TV goes into art mode -> on state -> off state -> on state -> off state and so on.
Sometimes I evan get an 419 error from the toggle service.
After some time I can go into the art mode by pressing the power toggle again.

**Comment by idoaflalo** [comment]
> Toggling the power button few times generally is not a good idea. Anyway there are no difference in what implemented in your PR, because the button was just calling the `async_toggle` method that now is implemented at integration level to directly call `async_set_art_mode` instead of modify `async_turn_off` method called by the `async_toggle` method in `media_player` class . So, did you make the same test with your PR? I'm expecting same behavior!

With my PR I can toggle the power button non stop (even fast) and it responds very quick.
@ripburger can you verify it?

**Comment by ollo69** [comment]
Please try with [v0.6.4b1](https://github.com/ollo69/ha-samsungtv-smart/releases/tag/v0.6.4b1), just changed a condition check. This is absolutely identical to the logic inside your PR, just check that art mode is supported. This check is mandatory to not break turn off for TV that do not support art mode!!!

**Comment by ollo69** [comment]
Any news here?

**Comment by ripburger** [comment]
I'm traveling the US right now, so can't test it myself. Will give it a go when I'm back home!

**Comment by idoaflalo** [comment]
I tested the feature in the new version and still sometimes it turn the TV into art mode and sometimes not (turns the TV off completely).
I looked at your code and I don't know why it happens.
Thanks for investing your time on this feature but I will stick my branch for now.

**Comment by ollo69** [comment]
> Thanks for investing your time on this feature but I will stick to my branch for now

You could try changing the conditions in `toggle` method and if you find the right solution create a new PR to fix the issue.

**Comment by idoaflalo** [comment]
I have tried modifying the toggle function without any success (with every combination of conditions possible).
It looks like the toggle function is affected by the state in HA which is not syncorinized with the TV because of the update delay written in the code, causing the code to invoke the regular toggle function and turns off the TV completely.
I updated the PR to the current master.

**Comment by ollo69** [comment]
Toggle method just do [this](https://github.com/home-assistant/core/blob/0248a8710f347401dbafa47d350657781a66dba1/homeassistant/components/media_player/__init__.py#L848) when called if method is not overriden, no special logic inside. When you press the power button on user interface, it just call the toggle method (not turn off), that will call the `async_turn_off` method when it consider the TV on. It is not correct override `async_turn_off` method, because this is used also by `turn_off` service that should always turn off the TV (if a user want go in Frame mode using service, can call the dedicated one).

**Comment by idoaflalo** [comment]
> Toggle method just do [this](https://github.com/home-assistant/core/blob/0248a8710f347401dbafa47d350657781a66dba1/homeassistant/components/media_player/__init__.py#L848) when called if method is not overriden, no special logic inside. When you press the power button on user interface, it just call the toggle method (not turn off), that will call the `async_turn_off` method when it consider the TV on. It is not correct override `async_turn_off` method, because this is used also by `turn_off` service that should always turn off the TV (if a user want go in Frame mode using service, can call the dedicated one).

Got your point. I will try to play with it more during the week.

**Comment by idoaflalo** [comment]
I have just debugged the integration and found the problem to the behavior I have tried to explain in the previous messages.

https://github.com/home-assistant/frontend/blob/fe46f759c937a101e5720aa3ccfcd3903ebc0051/src/panels/lovelace/entity-rows/hui-media-player-entity-row.ts#L317

They don't use the `toggle` service, instead they use the `turn_off` and `turn_on` services which skips the `toggle` function.
That's why it didn't work for me.
I don't have a better solution right now.

**Comment by ollo69** [comment]
> They don't use the `toggle` service, instead they use the `turn_off` and `turn_on` services which skips the `toggle` function.

I think that this should be addressed opening an issue to HomeAssistant UI. As alternative you can use a different control as [mini-media-player](https://github.com/kalkih/mini-media-player) that use toggle service to toggle status and also provide many additional feature compared to the native control.

**Comment by idoaflalo** [comment]
I will try this component and update the PR accordingly.
Thanks for your support!

**Comment by idoaflalo** [comment]
> > They don't use the `toggle` service, instead they use the `turn_off` and `turn_on` services which skips the `toggle` function.
> 
> I think that this should be addressed opening an issue to HomeAssistant UI. As alternative you can use a different control as [mini-media-player](https://github.com/kalkih/mini-media-player) that use toggle service to toggle status and also provide many additional feature compared to the native control.

As you recommended, it is working now.
Thank you so much!

**Comment by deadrubberboy** [comment]
> > They don't use the `toggle` service, instead they use the `turn_off` and `turn_on` services which skips the `toggle` function.
> 
> I think that this should be addressed opening an issue to HomeAssistant UI. As alternative you can use a different control as [mini-media-player](https://github.com/kalkih/mini-media-player) that use toggle service to toggle status and also provide many additional feature compared to the native control.

Hi. Can you explain more how I would do this? I am new and do not understand what "use a different control" means

**Pull request closed without merging**
